[DS-1653] - Initial implementation of the WS Override plugin Manager
YCloudYUSA/y_lb pull request #245
Opened 2024-09-16 12:55 UTC by aleevas

Jira issue [DS-1653](https://yusa.atlassian.net/browse/DS-1653)

How to check:

- [ ] In the custom module please create a new yml file with `{module_name}.ws_lb_override.yml` the next structure:
```yml
{module_name}.{component_id}_override:
  block_type: lb_testimonials
  library: {module_name}/lb_testimonials_override
  override: false
  active_colorways:
    - small_y*
```
- [ ] clear the cache
- [ ] create a new library for override rules
![image](https://github.com/user-attachments/assets/bf2af1ae-a8db-45d7-ab55-b0541a867053)

- [ ] In the files for this library add a rule to override (just for example)
![image](https://github.com/user-attachments/assets/75288b3d-065c-4b10-9207-74fee062d3e7)

- [ ] go to the LP with LB
- [ ] in the LB settings, please select WS Samll colorway
- [ ] save the LB
- [ ]  verify that your override rules are applied

2024-09-16 15:00 UTC, rollki approved these changes
LGTM, thanks @aleevas

2024-09-17 13:10 UTC, aleevas commented on src/WSOverrideLayoutBuilder.php
> +          if (str_contains($active_colorway, '*')) {
@anpolimus improved at this commit [af14e53be0c5f1b2966b2a48c014e800ec8b46aa](https://github.com/YCloudYUSA/y_lb/pull/245/commits/af14e53be0c5f1b2966b2a48c014e800ec8b46aa)
cc @rollki

2024-09-17 15:36 UTC, podarok requested changes
this will be 3.8.0 version of y_lb and https://git.drupalcode.org/project/ws_small_y/-/merge_requests/1 should have dependency in composer.json from y_lb >= 3.8

2024-09-17 16:14 UTC, anpolimus approved these changes

2024-09-17 16:15 UTC, anpolimus commented on src/WSOverrideLayoutBuilder.php
> +          if (str_contains($active_colorway, '*')) {
@aleevas thank you. Now this PR is approved from my end.

2024-09-18 13:12 UTC, rollki approved these changes

2024-09-19 13:28 UTC, podarok approved these changes

2024-09-19 13:33 UTC, merged